### ISSUE TITLE
게시글 생성시 태그 입력 띄어쓰기 구분하는 방식을 어떻게 해야할지 알려주세요

### ISSUE THREAD

**Issue by ssssksss** [four-Rest/Img_Forest_Backend#45]
요구사항으로 velog처럼 입력시 태그가 단어 형태로 보이게 요청
velog에서는 띄어쓰기를 포함한 태그가 존재
`띄어쓰기 태그` `오늘은 날씨가 맑음` 이런 형태의 태그가 가능
백엔드 로직을 대략적으로 파악한 바로는 FE에서 문자열로 보내면 BE에서는 띄어쓰기로 구분해서 태그를 저장하는 방식으로 파악하였는데 맞을까요?

![image](https://github.com/four-Rest/Img_Forest_Backend/assets/60907697/380baa00-f967-41d7-b948-4c8d33a28721)
원하시는 요구사항에 맞게 어떤 방식으로 값으로 보내주어야 할지 알려주세요

1. `오늘도, 날씨가, 맑음, 태그명` => 문자열 형태, 띄어쓰기가 포함된 단어가 없는 방식, 구분자(,)
2. `오늘도 날씨가 맑음 태그명` => 문자열 형태, 띄어쓰기가 포함된 단어가 없는 방식, 구분자(띄어쓰기)
3. `오늘도 날씨가 맑음, 태그명` => 문자열 형태, 띄어쓰기가 포함된 단어가 있는 방식, 구분자(,)

추가적으로
1. 게시글 수정시 태그에 아무런 값을 보내지 않아도 이전의 태그값들이 사라지지 않고 존재하고 있습니다.
2. 게시글 수정시 가격 수정이 되지를 않는 것 같습니다.

**Comment by Bang210** [comment]
현재 구현되어 있는 방식은 수경님이 파악하신 대로가 맞습니다.

3의 방식을 배열의 형태로 보내주도록 구현해주실 수 있을까요?
{오늘도 날씨가 맑음, 태그명}
백엔드 로직도 해당 방식에 맞게 수정하겠습니다.

추가1
해당 부분 수정해놓겠습니다.

추가2
유료 게시글의 경우 이미지파일과 가격 수정을 불가능하게 설정하는게 맞는 것 같은데, 이에 대한 의견 부탁드립니다.

**Comment by tallguy188** [comment]
추가2
유료 게시글의 경우 이미지파일은 일단 수정이 안되게하는게 맞습니다. 이미 구매한 사람이 다시 다운로드 받고 싶어서 들어와도 다운로드가 가능해야되는데, 이 경우 자신이 구매한 이미지가 다른 이미지로 바뀌는 상황이 생기면 안될 것 같습니다. 가격 수정도 사실 수정 가능과 불가능의 방향 두가지가 모두 존재하는데 이미지 파일을 수정 안되게 하면 가격 역시 수정 불가하게 통일하는게 나을 것 같습니다.
